/**
 * 観光ステップ — 17広域自治体 → 市・郡・区チップ
 * label: 日本語表示 / query: Places・日程検索用（韓国行政区域名）
 */
window.REGION_AREA_LABELS = {
  seoul: "ソウル特別市",
  busan: "釜山広域市",
  daegu: "大邱広域市",
  incheon: "仁川広域市",
  gwangju: "光州広域市",
  daejeon: "大田広域市",
  ulsan: "蔚山広域市",
  sejong: "世宗特別自治市",
  gyeonggi: "京畿道",
  gangwon: "江原特別自治道",
  chungbuk: "忠清北道",
  chungnam: "忠清南道",
  jeonbuk: "全北特別自治道",
  jeonnam: "全羅南道",
  gyeongbuk: "慶尚北道",
  gyeongnam: "慶尚南道",
  jeju: "済州特別自治道",
};

// Existing planner/search logic still groups some regions by broad tourism buckets.
window.REGION_BUCKET_BY_AREA = {
  seoul: "seoul",
  busan: "gyeongsang",
  daegu: "gyeongsang",
  incheon: "incheon",
  gwangju: "jeolla",
  daejeon: "chungcheong",
  ulsan: "gyeongsang",
  sejong: "chungcheong",
  gyeonggi: "gyeonggi",
  gangwon: "gangwon",
  chungbuk: "chungcheong",
  chungnam: "chungcheong",
  jeonbuk: "jeolla",
  jeonnam: "jeolla",
  gyeongbuk: "gyeongsang",
  gyeongnam: "gyeongsang",
  jeju: "jeju",
};

/** @type {Record<string, { id: string, label: string, query: string }[]>} */
window.REGION_CITY_OPTIONS = {
  seoul: [
    { id: "jongno", label: "鍾路区", query: "서울 종로구" },
    { id: "jung", label: "中区（明洞）", query: "서울 중구" },
    { id: "yongsan", label: "龍山区（梨泰院）", query: "서울 용산구" },
    { id: "seongdong", label: "城東区（聖水）", query: "서울 성동구" },
    { id: "gwangjin", label: "広津区", query: "서울 광진구" },
    { id: "dongdaemun", label: "東大門区", query: "서울 동대문구" },
    { id: "jungnang", label: "中浪区", query: "서울 중랑구" },
    { id: "seongbuk", label: "城北区", query: "서울 성북구" },
    { id: "gangbuk", label: "江北区", query: "서울 강북구" },
    { id: "dobong", label: "道峰区", query: "서울 도봉구" },
    { id: "nowon", label: "蘆原区", query: "서울 노원구" },
    { id: "eunpyeong", label: "恩平区", query: "서울 은평구" },
    { id: "seodaemun", label: "西大門区", query: "서울 서대문구" },
    { id: "mapo", label: "麻浦区（弘大）", query: "서울 마포구" },
    { id: "yangcheon", label: "陽川区", query: "서울 양천구" },
    { id: "gangseo", label: "江西区", query: "서울 강서구" },
    { id: "guro", label: "九老区", query: "서울 구로구" },
    { id: "geumcheon", label: "衿川区", query: "서울 금천구" },
    { id: "yeongdeungpo", label: "永登浦区", query: "서울 영등포구" },
    { id: "dongjak", label: "銅雀区", query: "서울 동작구" },
    { id: "gwanak", label: "冠岳区", query: "서울 관악구" },
    { id: "seocho", label: "瑞草区", query: "서울 서초구" },
    { id: "gangnam", label: "江南区", query: "서울 강남구" },
    { id: "songpa", label: "松坡区（蚕室）", query: "서울 송파구" },
    { id: "gangdong", label: "江東区", query: "서울 강동구" },
  ],
  busan: [
    { id: "jung", label: "中区", query: "부산 중구" },
    { id: "seo", label: "西区", query: "부산 서구" },
    { id: "dong", label: "東区", query: "부산 동구" },
    { id: "yeongdo", label: "影島区", query: "부산 영도구" },
    { id: "busanjin", label: "釜山鎮区（西面）", query: "부산 부산진구" },
    { id: "dongnae", label: "東莱区", query: "부산 동래구" },
    { id: "nam", label: "南区", query: "부산 남구" },
    { id: "buk", label: "北区", query: "부산 북구" },
    { id: "haeundae", label: "海雲台区", query: "부산 해운대구" },
    { id: "saha", label: "沙下区", query: "부산 사하구" },
    { id: "geumjeong", label: "金井区", query: "부산 금정구" },
    { id: "gangseo", label: "江西区", query: "부산 강서구" },
    { id: "yeonje", label: "蓮堤区", query: "부산 연제구" },
    { id: "suyeong", label: "水営区", query: "부산 수영구" },
    { id: "sasang", label: "沙上区", query: "부산 사상구" },
    { id: "gijang", label: "機張郡", query: "부산 기장군" },
  ],
  daegu: [
    { id: "jung", label: "中区", query: "대구 중구" },
    { id: "dong", label: "東区", query: "대구 동구" },
    { id: "seo", label: "西区", query: "대구 서구" },
    { id: "nam", label: "南区", query: "대구 남구" },
    { id: "buk", label: "北区", query: "대구 북구" },
    { id: "suseong", label: "寿城区", query: "대구 수성구" },
    { id: "dalseo", label: "達西区", query: "대구 달서구" },
    { id: "dalseong", label: "達城郡", query: "대구 달성군" },
    { id: "gunwi", label: "軍威郡", query: "대구 군위군" },
  ],
  incheon: [
    { id: "yeonsu", label: "延寿区（松島）", query: "인천 연수구" },
    { id: "namdong", label: "南洞区", query: "인천 남동구" },
    { id: "michuhol", label: "弥鄒忽区（文鶴）", query: "인천 미추홀구" },
    { id: "bupyeong", label: "富平区", query: "인천 부평구" },
    { id: "gyeyang", label: "桂陽区", query: "인천 계양구" },
    { id: "seogu", label: "西区", query: "인천 서구" },
    { id: "jung", label: "中区（月尾島）", query: "인천 중구" },
    { id: "dong", label: "東区", query: "인천 동구" },
    { id: "geomdan", label: "黔丹区", query: "인천 검단구" },
    { id: "ganghwa", label: "江華郡", query: "강화군" },
    { id: "ongjin", label: "甕津郡", query: "옹진군" },
  ],
  gwangju: [
    { id: "dong", label: "東区", query: "광주 동구" },
    { id: "seo", label: "西区", query: "광주 서구" },
    { id: "nam", label: "南区", query: "광주 남구" },
    { id: "buk", label: "北区", query: "광주 북구" },
    { id: "gwangsan", label: "光山区", query: "광주 광산구" },
  ],
  daejeon: [
    { id: "dong", label: "東区", query: "대전 동구" },
    { id: "jung", label: "中区", query: "대전 중구" },
    { id: "seo", label: "西区", query: "대전 서구" },
    { id: "yuseong", label: "儒城区", query: "대전 유성구" },
    { id: "daedeok", label: "大徳区", query: "대전 대덕구" },
  ],
  ulsan: [
    { id: "jung", label: "中区", query: "울산 중구" },
    { id: "nam", label: "南区", query: "울산 남구" },
    { id: "dong", label: "東区", query: "울산 동구" },
    { id: "buk", label: "北区", query: "울산 북구" },
    { id: "ulju", label: "蔚州郡", query: "울산 울주군" },
  ],
  sejong: [
    { id: "sejong", label: "世宗特別自治市", query: "세종특별자치시" },
  ],
  gyeonggi: [
    { id: "suwon", label: "水原市", query: "수원시" },
    { id: "seongnam", label: "城南市", query: "성남시" },
    { id: "goyang", label: "高陽市", query: "고양시" },
    { id: "yongin", label: "龍仁市", query: "용인시" },
    { id: "bucheon", label: "富川市", query: "부천시" },
    { id: "ansan", label: "安山市", query: "안산시" },
    { id: "anyang", label: "安養市", query: "안양시" },
    { id: "namyangju", label: "南楊州市", query: "남양주시" },
    { id: "hwaseong", label: "華城市", query: "화성시" },
    { id: "pyeongtaek", label: "平沢市", query: "평택시" },
    { id: "uijeongbu", label: "議政府市", query: "의정부시" },
    { id: "siheung", label: "始興市", query: "시흥시" },
    { id: "paju", label: "坡州市", query: "파주시" },
    { id: "gimpo", label: "金浦市", query: "김포시" },
    { id: "gwangmyeong", label: "光明市", query: "광명시" },
    { id: "gwangju_si", label: "広州市（京畿道）", query: "경기도 광주시" },
    { id: "gunpo", label: "軍浦市", query: "군포시" },
    { id: "osan", label: "烏山市", query: "오산시" },
    { id: "icheon", label: "利川市", query: "이천시" },
    { id: "anseong", label: "安城市", query: "안성시" },
    { id: "guri", label: "九里市", query: "구리시" },
    { id: "uiwang", label: "義王市", query: "의왕시" },
    { id: "hanam", label: "河南市", query: "하남시" },
    { id: "pocheon", label: "抱川市", query: "포천시" },
    { id: "yangju", label: "楊州市", query: "양주시" },
    { id: "dongducheon", label: "東豆川市", query: "동두천시" },
    { id: "gwacheon", label: "果川市", query: "과천시" },
    { id: "yeoju", label: "驪州市", query: "여주시" },
    { id: "gapyeong", label: "加平郡", query: "가평군" },
    { id: "yangpyeong", label: "楊平郡", query: "양평군" },
    { id: "yeoncheon", label: "漣川郡", query: "연천군" },
  ],
  gangwon: [
    { id: "chuncheon", label: "春川市", query: "춘천시" },
    { id: "wonju", label: "原州市", query: "원주시" },
    { id: "gangneung", label: "江陵市", query: "강릉시" },
    { id: "donghae", label: "東海市", query: "동해시" },
    { id: "taebaek", label: "太白市", query: "태백시" },
    { id: "sokcho", label: "束草市", query: "속초시" },
    { id: "samcheok", label: "三陟市", query: "삼척시" },
    { id: "hongcheon", label: "洪川郡", query: "홍천군" },
    { id: "hoengseong", label: "横城郡", query: "횡성군" },
    { id: "yeongwol", label: "寧越郡", query: "영월군" },
    { id: "pyeongchang", label: "平昌郡", query: "평창군" },
    { id: "jeongseon", label: "旌善郡", query: "정선군" },
    { id: "cheorwon", label: "鉄原郡", query: "철원군" },
    { id: "hwacheon", label: "華川郡", query: "화천군" },
    { id: "yanggu", label: "楊口郡", query: "양구군" },
    { id: "inje", label: "麟蹄郡", query: "인제군" },
    { id: "goseong", label: "高城郡", query: "강원 고성군" },
    { id: "yangyang", label: "襄陽郡", query: "양양군" },
  ],
  chungbuk: [
    { id: "cheongju", label: "清州市", query: "청주시" },
    { id: "chungju", label: "忠州市", query: "충주시" },
    { id: "jecheon", label: "堤川市", query: "제천시" },
    { id: "boeun", label: "報恩郡", query: "보은군" },
    { id: "okcheon", label: "沃川郡", query: "옥천군" },
    { id: "yeongdong", label: "永同郡", query: "영동군" },
    { id: "jeungpyeong", label: "曽坪郡", query: "증평군" },
    { id: "jincheon", label: "鎮川郡", query: "진천군" },
    { id: "goesan", label: "槐山郡", query: "괴산군" },
    { id: "eumseong", label: "陰城郡", query: "음성군" },
    { id: "danyang", label: "丹陽郡", query: "단양군" },
  ],
  chungnam: [
    { id: "cheonan", label: "天安市", query: "천안시" },
    { id: "gongju", label: "公州市", query: "공주시" },
    { id: "boryeong", label: "保寧市", query: "보령시" },
    { id: "asan", label: "牙山市", query: "아산시" },
    { id: "seosan", label: "瑞山市", query: "서산시" },
    { id: "nonsan", label: "論山市", query: "논산시" },
    { id: "gyeryong", label: "鶏龍市", query: "계룡시" },
    { id: "dangjin", label: "唐津市", query: "당진시" },
    { id: "geumsan", label: "錦山郡", query: "금산군" },
    { id: "buyeo", label: "扶余郡", query: "부여군" },
    { id: "seocheon", label: "舒川郡", query: "서천군" },
    { id: "cheongyang", label: "青陽郡", query: "청양군" },
    { id: "hongseong", label: "洪城郡", query: "홍성군" },
    { id: "yesan", label: "礼山郡", query: "예산군" },
    { id: "taean", label: "泰安郡", query: "태안군" },
  ],
  jeonbuk: [
    { id: "jeonju", label: "全州市", query: "전주시" },
    { id: "gunsan", label: "群山市", query: "군산시" },
    { id: "iksan", label: "益山市", query: "익산시" },
    { id: "jeongeup", label: "井邑市", query: "정읍시" },
    { id: "namwon", label: "南原市", query: "남원시" },
    { id: "gimje", label: "金堤市", query: "김제시" },
    { id: "wanju", label: "完州郡", query: "완주군" },
    { id: "jinan", label: "鎮安郡", query: "진안군" },
    { id: "muju", label: "茂朱郡", query: "무주군" },
    { id: "jangsu", label: "長水郡", query: "장수군" },
    { id: "imsil", label: "任実郡", query: "임실군" },
    { id: "sunchang", label: "淳昌郡", query: "순창군" },
    { id: "gochang", label: "高敞郡", query: "고창군" },
    { id: "buan", label: "扶安郡", query: "부안군" },
  ],
  jeonnam: [
    { id: "mokpo", label: "木浦市", query: "목포시" },
    { id: "yeosu", label: "麗水市", query: "여수시" },
    { id: "suncheon", label: "順天市", query: "순천시" },
    { id: "naju", label: "羅州市", query: "나주시" },
    { id: "gwangyang", label: "光陽市", query: "광양시" },
    { id: "damyang", label: "潭陽郡", query: "담양군" },
    { id: "gokseong", label: "谷城郡", query: "곡성군" },
    { id: "gurye", label: "求礼郡", query: "구례군" },
    { id: "goheung", label: "高興郡", query: "고흥군" },
    { id: "boseong", label: "宝城郡", query: "보성군" },
    { id: "hwasun", label: "和順郡", query: "화순군" },
    { id: "jangheung", label: "長興郡", query: "장흥군" },
    { id: "gangjin", label: "康津郡", query: "강진군" },
    { id: "haenam", label: "海南郡", query: "해남군" },
    { id: "yeongam", label: "霊岩郡", query: "영암군" },
    { id: "muan", label: "務安郡", query: "무안군" },
    { id: "hampyeong", label: "咸平郡", query: "함평군" },
    { id: "yeonggwang", label: "霊光郡", query: "영광군" },
    { id: "jangseong", label: "長城郡", query: "장성군" },
    { id: "wando", label: "莞島郡", query: "완도군" },
    { id: "jindo", label: "珍島郡", query: "진도군" },
    { id: "sinan", label: "新安郡", query: "신안군" },
  ],
  gyeongbuk: [
    { id: "pohang", label: "浦項市", query: "포항시" },
    { id: "gyeongju", label: "慶州市", query: "경주시" },
    { id: "gimcheon", label: "金泉市", query: "김천시" },
    { id: "andong", label: "安東市", query: "안동시" },
    { id: "gumi", label: "亀尾市", query: "구미시" },
    { id: "yeongju", label: "栄州市", query: "영주시" },
    { id: "yeongcheon", label: "永川市", query: "영천시" },
    { id: "sangju", label: "尚州市", query: "상주시" },
    { id: "mungyeong", label: "聞慶市", query: "문경시" },
    { id: "gyeongsan", label: "慶山市", query: "경산시" },
    { id: "uiseong", label: "義城郡", query: "의성군" },
    { id: "cheongsong", label: "青松郡", query: "청송군" },
    { id: "yeongyang", label: "英陽郡", query: "영양군" },
    { id: "yeongdeok", label: "盈徳郡", query: "영덕군" },
    { id: "cheongdo", label: "清道郡", query: "청도군" },
    { id: "goryeong", label: "高霊郡", query: "고령군" },
    { id: "seongju", label: "星州郡", query: "성주군" },
    { id: "chilgok", label: "漆谷郡", query: "칠곡군" },
    { id: "yecheon", label: "醴泉郡", query: "예천군" },
    { id: "bonghwa", label: "奉化郡", query: "봉화군" },
    { id: "uljin", label: "蔚珍郡", query: "울진군" },
    { id: "ulleung", label: "鬱陵郡", query: "울릉군" },
  ],
  gyeongnam: [
    { id: "changwon", label: "昌原市", query: "창원시" },
    { id: "jinju", label: "晋州市", query: "진주시" },
    { id: "tongyeong", label: "統営市", query: "통영시" },
    { id: "sacheon", label: "泗川市", query: "사천시" },
    { id: "gimhae", label: "金海市", query: "김해시" },
    { id: "miryang", label: "密陽市", query: "밀양시" },
    { id: "geoje", label: "巨済市", query: "거제시" },
    { id: "yangsan", label: "梁山市", query: "양산시" },
    { id: "uiryeong", label: "宜寧郡", query: "의령군" },
    { id: "haman", label: "咸安郡", query: "함안군" },
    { id: "changnyeong", label: "昌寧郡", query: "창녕군" },
    { id: "goseong", label: "固城郡", query: "경남 고성군" },
    { id: "namhae", label: "南海郡", query: "남해군" },
    { id: "hadong", label: "河東郡", query: "하동군" },
    { id: "sancheong", label: "山清郡", query: "산청군" },
    { id: "hamyang", label: "咸陽郡", query: "함양군" },
    { id: "geochang", label: "居昌郡", query: "거창군" },
    { id: "hapcheon", label: "陜川郡", query: "합천군" },
  ],
  jeju: [
    { id: "jeju_city", label: "済州市", query: "제주시" },
    { id: "seogwipo", label: "西帰浦市", query: "서귀포시" },
  ],
};
