# Generated by Django 5.2.14 on 2026-05-14 04:50

import django.db.models.deletion
import pgvector.django.vector
import tour_api.models
import uuid
from django.db import migrations, models


def create_pgvector_extension(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("CREATE EXTENSION IF NOT EXISTS vector")


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_pgvector_extension, migrations.RunPython.noop),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anonymous_id', models.CharField(db_index=True, default=tour_api.models._anonymous_id, max_length=64)),
                ('reply_language', models.CharField(default='日本語', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=16)),
                ('current_latitude', models.FloatField(blank=True, null=True)),
                ('current_longitude', models.FloatField(blank=True, null=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=16)),
                ('content', models.TextField()),
                ('translated_ko', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=32)),
                ('keyword', models.CharField(blank=True, max_length=128)),
                ('sources_used', models.JSONField(blank=True, default=list)),
                ('rag_count', models.PositiveIntegerField(default=0)),
                ('places_count', models.PositiveIntegerField(default=0)),
                ('is_fallback', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tour_api.chatsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(default='jsonl', max_length=32)),
                ('source_name', models.CharField(db_index=True, max_length=255)),
                ('source_uri', models.CharField(blank=True, max_length=512)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('domain', models.CharField(blank=True, max_length=64)),
                ('category', models.CharField(blank=True, max_length=32)),
                ('area', models.CharField(blank=True, max_length=64)),
                ('language', models.CharField(default='ja', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['source_name', 'id'],
                'constraints': [models.UniqueConstraint(fields=('source_type', 'source_name'), name='uniq_knowledge_source')],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=128)),
                ('chunk_index', models.PositiveIntegerField(default=0)),
                ('question_ja', models.TextField(blank=True)),
                ('answer_ja', models.TextField(blank=True)),
                ('answer_ko', models.TextField(blank=True)),
                ('chunk_text', models.TextField()),
                ('category', models.CharField(blank=True, max_length=32)),
                ('area', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='tour_api.knowledgedocument')),
            ],
            options={
                'ordering': ['document_id', 'chunk_index'],
            },
        ),
        migrations.CreateModel(
            name='RetrievalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('backend', models.CharField(max_length=32)),
                ('category_filter', models.CharField(blank=True, max_length=32)),
                ('area_filter', models.CharField(blank=True, max_length=64)),
                ('top_k', models.PositiveSmallIntegerField(default=5)),
                ('result_chunk_ids', models.JSONField(blank=True, default=list)),
                ('result_scores', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retrieval_logs', to='tour_api.chatmessage')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retrieval_logs', to='tour_api.chatsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TravelerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_level', models.CharField(blank=True, max_length=32)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('personality_type', models.CharField(blank=True, max_length=32)),
                ('home_country', models.CharField(blank=True, max_length=64)),
                ('travel_style', models.CharField(blank=True, max_length=64)),
                ('hotel_booked', models.BooleanField(blank=True, null=True)),
                ('arrival_airport', models.CharField(blank=True, max_length=64)),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('return_time', models.DateTimeField(blank=True, null=True)),
                ('extra_preferences', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='traveler_profile', to='tour_api.chatsession')),
            ],
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'created_at'], name='tour_api_ch_session_fcd8b2_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['role', 'created_at'], name='tour_api_ch_role_607414_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgechunk',
            index=models.Index(fields=['category'], name='tour_api_kn_categor_523dc6_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgechunk',
            index=models.Index(fields=['area'], name='tour_api_kn_area_2840a5_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgechunk',
            index=models.Index(fields=['external_id'], name='tour_api_kn_externa_7d8731_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgechunk',
            index=models.Index(fields=['document', 'chunk_index'], name='tour_api_kn_documen_17b6b7_idx'),
        ),
        migrations.AddConstraint(
            model_name='knowledgechunk',
            constraint=models.UniqueConstraint(fields=('document', 'external_id'), name='uniq_document_external_id'),
        ),
        migrations.AddIndex(
            model_name='retrievallog',
            index=models.Index(fields=['backend', 'created_at'], name='tour_api_re_backend_5583f9_idx'),
        ),
        migrations.AddIndex(
            model_name='retrievallog',
            index=models.Index(fields=['session', 'created_at'], name='tour_api_re_session_18f131_idx'),
        ),
    ]
