# Generated by Django 5.2.14 on 2026-06-03 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tour_api", "0002_travelplansnapshot"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="travelplansnapshot",
            new_name="tour_api_tr_user_id_e9c202_idx",
            old_name="tour_api_tr_user_id_2a6e67_idx",
        ),
        migrations.RenameIndex(
            model_name="travelplansnapshot",
            new_name="tour_api_tr_session_0f7d15_idx",
            old_name="tour_api_tr_session_e4a807_idx",
        ),
    ]
